### ISSUE TITLE
Does this example work?

### ISSUE THREAD

**Issue by dangtony98** [ardisaurus/next-js-argon2#1]
Hey @ardisaurus!

Stumbled into this repo whilst looking for ways to implement argon2 into our Next.js app - was hoping that this example would work but it doesn't seem to run properly.

Here's the error I'm getting:

<img width="894" alt="Screen Shot 2023-01-29 at 3 45 06 PM" src="https://user-images.githubusercontent.com/25857006/215315361-6a354716-309e-43d6-be56-00623b7d1e7e.png">

Thanks!

**Comment by ardisaurus** [comment]
Hi @dangtony98, I just updated the next and react version, it should be work by now

**Comment by dangtony98** [comment]
@ardisaurus

Wow many thanks for updating this so fast! - It works now :)
